name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache npm repository
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Installing packages
        run: npm ci
      - name: Build site
        run: env NODE_ENV=production npm run build
      - name: rsync dist
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: .vitepress/dist/
          remote_path: ${{ secrets.POST_PATH }}
          remote_host: ${{ vars.POST_HOST }}
          remote_user: ${{ secrets.POST_USER }}
          remote_key: ${{ secrets.POST_KEY }}
      - uses: actions/checkout@v3

      - id: release
        uses: CatChen/node-package-release-action@v1
        with:
          release-type: patch
          prerelease: false
          update-shorthand-release: false
          skip-if-no-diff: true

      - env:
          TAG: ${{ steps.release.outputs.tag }}
          SKIPPED: ${{ steps.release.outputs.skipped }}
        run: |
          if [[ "$SKIPPED"='true' ]]
          then
            echo 'Release is skipped.'
          else
            echo "Release $TAG successfully."
          fi


# only run one of these at a time
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
